language: php
dist: trusty

sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - hhvm-3.30

matrix:
    allow_failures:
        - php: hhvm
    include:
        - php: "5.3"
          dist: precise

before_install:
    - composer self-update

install:
    - |
      if [[ "${TRAVIS_PHP_VERSION}" = hhvm* ]]; then
        # PHPUnit 6.0 is incompatible with HHVM because of
        # Uncaught Error: array_creation_expression is not allowed in write context
        # in vendor/phpunit/phpunit/src/Framework/TestCase.php:1273
        composer require --no-update 'phpunit/phpunit:^5.7'

        # symfony/console 4.0 (dependency of php-coveralls) relies on is_iterable()
        # function, added in PHP 7.1.0 and absent in HHVM
        composer require --no-update 'symfony/console:^3.0'

        # htmlpurifier 4.10.0 is broken on HHVM
        # https://github.com/ezyang/htmlpurifier/issues/169
        composer require --no-update 'ezyang/htmlpurifier:dev-master#89b3fe4'
      fi
    - |
      if [[ "${TRAVIS_PHP_VERSION}" = 5.3 ]]; then
        # htmlpurifier 4.11.0 is incompatible with PHP < 5.4
        # https://github.com/ezyang/htmlpurifier/pull/225
        composer require --no-update 'ezyang/htmlpurifier:4.10.0'
      fi
    - composer install

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - if [ -f "vendor/bin/php-coveralls" ]; then php vendor/bin/php-coveralls -v; else vendor/bin/coveralls -v; fi
