name: build

on: [push, pull_request]

jobs:
    run:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            fail-fast: false
            matrix:
                operating-system: ['ubuntu-16.04']
                php-versions: ['7.4', '7.3', '7.2', '7.1', '7.0', '5.6', '5.5', '5.4', '5.3']

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, intl, dom
                  ini-values: max_execution_time=0
                  coverage: xdebug

            - name: Install dependencies
              run: composer install

            - name: Run tests
              run: |
                mkdir -p build/logs
                COMPOSER_PROCESS_TIMEOUT=0 composer test -- --coverage-clover build/logs/clover.xml

            - name: Upload coverage results to Coveralls
              env:
                COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                if [ -f "vendor/bin/php-coveralls" ]; then php vendor/bin/php-coveralls -v; fi
